[build]
  command = "npm install && npm run build"
  publish = "build"
  base = "client"

[[redirects]]
  from = "/api/*"
  to = "/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
